/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccountForm: typeof import('./src/components/AccountForm.vue')['default']
    Button: typeof import('./src/components/ui/button/Button.vue')['default']
    copy: typeof import('./src/components/TheInput copy.vue')['default']
    FormControl: typeof import('./src/components/ui/form/FormControl.vue')['default']
    FormDescription: typeof import('./src/components/ui/form/FormDescription.vue')['default']
    FormItem: typeof import('./src/components/ui/form/FormItem.vue')['default']
    FormLabel: typeof import('./src/components/ui/form/FormLabel.vue')['default']
    FormMessage: typeof import('./src/components/ui/form/FormMessage.vue')['default']
    Input: typeof import('./src/components/ui/input/Input.vue')['default']
    Label: typeof import('./src/components/ui/label/Label.vue')['default']
    PasswordInput: typeof import('./src/components/ui/password-input/PasswordInput.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./src/components/ui/select/Select.vue')['default']
    SelectContent: typeof import('./src/components/ui/select/SelectContent.vue')['default']
    SelectGroup: typeof import('./src/components/ui/select/SelectGroup.vue')['default']
    SelectItem: typeof import('./src/components/ui/select/SelectItem.vue')['default']
    SelectItemText: typeof import('./src/components/ui/select/SelectItemText.vue')['default']
    SelectLabel: typeof import('./src/components/ui/select/SelectLabel.vue')['default']
    SelectScrollDownButton: typeof import('./src/components/ui/select/SelectScrollDownButton.vue')['default']
    SelectScrollUpButton: typeof import('./src/components/ui/select/SelectScrollUpButton.vue')['default']
    SelectSeparator: typeof import('./src/components/ui/select/SelectSeparator.vue')['default']
    SelectTrigger: typeof import('./src/components/ui/select/SelectTrigger.vue')['default']
    SelectValue: typeof import('./src/components/ui/select/SelectValue.vue')['default']
    TheCounter: typeof import('./src/components/TheCounter.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheInput: typeof import('./src/components/TheInput.vue')['default']
    Toast: typeof import('./src/components/ui/toast/Toast.vue')['default']
    ToastAction: typeof import('./src/components/ui/toast/ToastAction.vue')['default']
    ToastClose: typeof import('./src/components/ui/toast/ToastClose.vue')['default']
    ToastDescription: typeof import('./src/components/ui/toast/ToastDescription.vue')['default']
    Toaster: typeof import('./src/components/ui/toast/Toaster.vue')['default']
    ToastProvider: typeof import('./src/components/ui/toast/ToastProvider.vue')['default']
    ToastTitle: typeof import('./src/components/ui/toast/ToastTitle.vue')['default']
    ToastViewport: typeof import('./src/components/ui/toast/ToastViewport.vue')['default']
  }
}
